---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.ctxmesh.ai
  resources:
  - agentdeployments
  - agentregistries
  - agentversions
  - mcptoolbindings
  - memorybindings
  - modelroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.ctxmesh.ai
  resources:
  - agentdeployments/finalizers
  - agentregistries/finalizers
  - mcptoolbindings/finalizers
  - modelroutes/finalizers
  verbs:
  - update
- apiGroups:
  - agents.ctxmesh.ai
  resources:
  - agentdeployments/status
  - agentregistries/status
  - mcptoolbindings/status
  - memorybindings/status
  - modelroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agents.ctxmesh.ai
  resources:
  - secretbindings
  - toolregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
