#!/usr/bin/env python3
"""Generate agent-engine Helm chart templates from `kustomize build config/default`.

Reads the rendered kustomize output on stdin, splits it into individual resource
documents, buckets each by component, and writes three template files:

  templates/crds.yaml          — the CustomResourceDefinitions (always installed)
  templates/control-plane.yaml — namespace, RBAC, controller-manager, gateway,
                                 metrics service (the production control plane)
  templates/dev-data-plane.yaml— statelayer (Valkey) + objectstore (MinIO) +
                                 their dev creds/config — gated by
                                 `.Values.devDataPlane.enabled` (dev/trial ONLY,
                                 PRD §23; production brings its own data plane)

THE NO-DRIFT INVARIANT: the resource *bodies* are copied verbatim from the
kustomize render — only two textual substitutions are applied, and only to make
the two knobs an operator needs into Helm values:

  1. the controller image `controller:latest`  -> {{ controllerManager image }}
  2. the install namespace `agent-engine-system`-> {{ .Values.namespace }}

Both default (in values.yaml) to the exact kustomize strings, so with defaults
`helm template` == `kustomize build config/default`. `make helm-verify` proves it.
"""
from __future__ import annotations

import os
import re
import sys

NS_KUSTOMIZE = "agent-engine-system"
IMG_KUSTOMIZE = "controller:latest"

# Resources whose `control-plane:` label marks them as the bundled DEV data
# plane (in-cluster Valkey/MinIO). Production supplies its own — PRD §23 — so
# these are gated behind .Values.devDataPlane.enabled.
DEV_DATA_PLANE_LABELS = {"statelayer", "objectstore"}

GEN_BANNER = (
    "# ============================================================================\n"
    "# GENERATED by hack/gen-helm-chart.sh from `kustomize build config/default`.\n"
    "# DO NOT EDIT BY HAND. Change config/ then run `make helm-generate`.\n"
    "# No-drift is enforced by `make helm-verify` (chart == kustomize).\n"
    "# ============================================================================\n"
)


def control_plane_label(doc: str) -> str | None:
    """Return the value of the top-level `control-plane:` metadata label, if any."""
    # The first `control-plane:` under metadata.labels identifies the component.
    m = re.search(r"^    control-plane:\s*(\S+)", doc, re.MULTILINE)
    return m.group(1) if m else None


def kind_of(doc: str) -> str:
    m = re.search(r"^kind:\s*(\S+)", doc, re.MULTILINE)
    return m.group(1) if m else ""


def name_of(doc: str) -> str:
    m = re.search(r"^  name:\s*(\S+)", doc, re.MULTILINE)
    return m.group(1) if m else ""


def substitute(doc: str) -> str:
    """Apply the two value substitutions (image, namespace) to a resource body."""
    # Controller image -> Helm value (only the exact kustomize placeholder).
    doc = doc.replace(
        f"image: {IMG_KUSTOMIZE}",
        'image: {{ printf "%s:%s" .Values.controllerManager.image.repository '
        "(.Values.controllerManager.image.tag | default .Chart.AppVersion) }}",
    )
    # Install namespace -> Helm value. Match only the standalone token so we do
    # not touch e.g. a substring inside another name.
    doc = re.sub(
        rf"(\bnamespace:\s*){re.escape(NS_KUSTOMIZE)}\b",
        r"\1{{ .Values.namespace }}",
        doc,
    )
    # The Namespace object's own name + RoleBinding/ClusterRoleBinding subject
    # namespaces use `name:`/`namespace:` -> also parameterize the Namespace name.
    return doc


def substitute_namespace_object(doc: str) -> str:
    """For the Namespace resource, its `name:` is the install namespace too."""
    return re.sub(
        rf"(^  name:\s*){re.escape(NS_KUSTOMIZE)}\b",
        r"\1{{ .Values.namespace }}",
        doc,
        flags=re.MULTILINE,
    )


def subject_namespace(doc: str) -> str:
    """RBAC subjects reference the SA namespace via `namespace:` in subjects[]."""
    return re.sub(
        rf"(\bnamespace:\s*){re.escape(NS_KUSTOMIZE)}\b",
        r"\1{{ .Values.namespace }}",
        doc,
    )


def main() -> None:
    out_dir = os.environ["OUT_DIR"]
    raw = sys.stdin.read()
    docs = [d for d in raw.split("\n---\n") if d.strip()]

    crds, control_plane, dev_data_plane = [], [], []

    for doc in docs:
        doc = doc.strip("\n")
        kind = kind_of(doc)
        cp = control_plane_label(doc)

        # Apply substitutions to every doc uniformly (image + namespace fields).
        doc = substitute(doc)
        if kind == "Namespace":
            doc = substitute_namespace_object(doc)
        doc = subject_namespace(doc)

        if kind == "CustomResourceDefinition":
            crds.append(doc)
        elif cp in DEV_DATA_PLANE_LABELS:
            dev_data_plane.append(doc)
        else:
            control_plane.append(doc)

    # --- crds.yaml -----------------------------------------------------------
    with open(os.path.join(out_dir, "crds.yaml"), "w") as f:
        f.write(GEN_BANNER)
        f.write("{{- if .Values.crds.install }}\n")
        f.write("\n---\n".join(crds))
        f.write("\n{{- end }}\n")

    # --- control-plane.yaml --------------------------------------------------
    with open(os.path.join(out_dir, "control-plane.yaml"), "w") as f:
        f.write(GEN_BANNER)
        f.write("\n---\n".join(control_plane))
        f.write("\n")

    # --- dev-data-plane.yaml -------------------------------------------------
    # Gated: dev/trial ONLY (PRD §23). Production disables it and points the
    # controller at an externally-managed Valkey/MinIO (values seam).
    with open(os.path.join(out_dir, "dev-data-plane.yaml"), "w") as f:
        f.write(GEN_BANNER)
        f.write(
            "# The bundled in-cluster Valkey (statelayer) + MinIO (objectstore)"
            " are for\n# DEV / TRIAL ONLY (PRD §23). Deterministic dev creds,"
            " never real secrets.\n"
            "# Production sets devDataPlane.enabled=false and brings its own"
            " data plane.\n"
        )
        f.write("{{- if .Values.devDataPlane.enabled }}\n")
        f.write("\n---\n".join(dev_data_plane))
        f.write("\n{{- end }}\n")


if __name__ == "__main__":
    main()
