apiVersion: agents.ctxmesh.ai/v1alpha1
kind: AgentVersion
metadata:
  labels:
    app.kubernetes.io/name: ctxmesh
    app.kubernetes.io/managed-by: kustomize
  name: agentversion-sample
spec:
  # TODO(user): Add fields here
