import { describe, expect, it } from "vitest";

import fixtures from "./contract-fixtures.json";

// Contract-fixture guard (m18.4). `contract-fixtures.json` is generated by the Go
// golden test `TestContractFixtures` from the REAL BFF DTOs (their json tags), so
// these assertions pin the exact wire shapes the pages depend on. If a BFF DTO
// drifts, the Go golden test forces the fixture to regenerate; if the change
// breaks a shape a page relies on, one of these fails — the systemic fix for the
// mock-drift crashes that shipped in M17 (connect-provider `res.models` and
// mcp-approvals `res.approvals`).
//
// New rule: a component test for a BFF-backed page builds its fetch mock from
// these fixtures, never from a hand-authored shape.

describe("BFF contract fixtures", () => {
  it("ConnectProviderResponse nests provider.models as string[] (NOT flat res.models)", () => {
    const r = fixtures.ConnectProviderResponse;
    expect(r.provider).toBeDefined();
    expect(Array.isArray(r.provider.models)).toBe(true);
    expect(typeof r.provider.models[0]).toBe("string");
    expect(r.provider.secretName).toBeDefined();
    // The flat shape the crashed page assumed must NOT exist.
    expect((r as Record<string, unknown>).models).toBeUndefined();
  });

  it("MCPServerListResponse exposes servers AND items arrays (NOT res.approvals)", () => {
    const r = fixtures.MCPServerListResponse;
    expect(Array.isArray(r.servers)).toBe(true);
    expect(Array.isArray(r.items)).toBe(true);
    expect((r as Record<string, unknown>).approvals).toBeUndefined();
  });

  it("ProviderListResponse exposes providers AND items", () => {
    const r = fixtures.ProviderListResponse;
    expect(Array.isArray(r.providers)).toBe(true);
    expect(Array.isArray(r.items)).toBe(true);
  });

  it("AgentDetailResponse carries promptRef + modelRoute for the used-by graph", () => {
    const r = fixtures.AgentDetailResponse;
    expect(r).toHaveProperty("promptRef");
    expect(r).toHaveProperty("modelRoute");
    expect(r).toHaveProperty("role");
  });
});
