/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sruntime "k8s.io/apimachinery/pkg/runtime"
)

// AgentTeam is a NEW type (M64, ADR 0057) with no v1alpha1 history, so it is born directly in the
// storage version (v1beta1) as a SINGLE-version CRD — no deprecated spoke, no conversion. The
// CRD-version-parity guard (hack/check-crd-version-parity.sh) skips single-version CRDs.

// AgentTeamSupervisor identifies the orchestrating agent of a team.
type AgentTeamSupervisor struct {
	// agentRef is the name of a standing AgentDeployment (same namespace) that orchestrates the team
	// (its role should be "orchestrator"). It MUST be a member of the team's registryRef.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$`
	AgentRef string `json:"agentRef"`
}

// AgentTeamRosterEntry is one summonable sub-agent in a team's roster (ADR 0057 Door 1). In v1 it is a
// REFERENCE to a standing AgentDeployment (`agentRef`) — NOT an inline spec. It is kept a discriminated
// union so an `inline:` template arm (a non-deployed template executed by a generic executor) can be
// added later without a breaking change.
type AgentTeamRosterEntry struct {
	// name is the roster-local identifier the supervisor uses to summon this sub-agent (the delegate_to
	// `sub_agent` argument). Unique within the roster.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$`
	Name string `json:"name"`

	// agentRef is the name of a standing AgentDeployment (same namespace) this entry summons as a
	// sub-run. It MUST be a member of the team's registryRef.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$`
	AgentRef string `json:"agentRef"`

	// description is a short natural-language summary of what this sub-agent does. It is surfaced to the
	// supervisor's model at summon time so it can choose whom to delegate to.
	// +kubebuilder:validation:MaxLength=512
	// +optional
	Description string `json:"description,omitempty"`
}

// SpawnBudget bounds a team's on-demand delegation (ADR 0057 Door 2). maxFanOut + maxTotalSpawns are
// AGGREGATE ceilings enforced by a shared Valkey counter keyed by the root run (fail-closed);
// maxSpawnDepth bounds the spawn-tree depth (per-path, carried in the spawn envelope). A nil SpawnBudget
// (the block omitted) resolves to all defaults in the controller.
type SpawnBudget struct {
	// maxFanOut is the maximum number of sub-runs a single supervisor step may start. Defaults to 4.
	// +kubebuilder:default=4
	// +kubebuilder:validation:Minimum=1
	// +optional
	MaxFanOut int32 `json:"maxFanOut,omitempty"`

	// maxSpawnDepth is the maximum depth of the spawn tree (supervisor -> sub-agent -> ...), distinct
	// from A2A hop depth. Defaults to 3.
	// +kubebuilder:default=3
	// +kubebuilder:validation:Minimum=1
	// +optional
	MaxSpawnDepth int32 `json:"maxSpawnDepth,omitempty"`

	// maxTotalSpawns is the maximum number of sub-runs across the whole spawn tree of one root run.
	// Defaults to 20.
	// +kubebuilder:default=20
	// +kubebuilder:validation:Minimum=1
	// +optional
	MaxTotalSpawns int32 `json:"maxTotalSpawns,omitempty"`
}

// AgentTeamSpec defines the desired state of an AgentTeam (ADR 0057).
type AgentTeamSpec struct {
	// registryRef is the name of the AgentRegistry (same namespace) that is this team's trust boundary:
	// OBO (ADR 0033), the NetworkPolicy, and the `shared` memory scope (ADR 0035) are all
	// registry-scoped. The supervisor + every roster member MUST be members of it. The registry is
	// REFERENCED, never generated by the team; a sub-run inherits it as its Boundary.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9\-]*[a-z0-9])?$`
	RegistryRef string `json:"registryRef"`

	// supervisor is the orchestrating agent that summons the roster.
	Supervisor AgentTeamSupervisor `json:"supervisor"`

	// roster is the governed set of summonable sub-agents. At least one entry; names are unique
	// (listMapKey). Each entry references a standing AgentDeployment.
	// +listType=map
	// +listMapKey=name
	// +kubebuilder:validation:MinItems=1
	// +kubebuilder:validation:MaxItems=64
	Roster []AgentTeamRosterEntry `json:"roster"`

	// spawnBudget bounds on-demand delegation (defaults maxFanOut=4, maxSpawnDepth=3,
	// maxTotalSpawns=20). A nil block resolves to all defaults in the controller.
	// +optional
	SpawnBudget *SpawnBudget `json:"spawnBudget,omitempty"`
}

// AgentTeamStatus defines the observed state of an AgentTeam.
type AgentTeamStatus struct {
	// registry echoes the resolved registryRef (the trust boundary), for convenience in listings.
	// +optional
	Registry string `json:"registry,omitempty"`

	// members lists the resolved supervisor + roster members that are Ready standing agents in the
	// registry. Populated by the controller on each reconcile.
	// +listType=atomic
	// +kubebuilder:validation:MaxItems=256
	// +optional
	Members []string `json:"members,omitempty"`

	// conditions reflect the team's reconciliation state. Ready=True means registryRef, the supervisor,
	// and every roster member resolved AND all are members of registryRef. Failure reasons include
	// RegistryNotFound, MemberNotFound, and NotARegistryMember.
	// +listType=map
	// +listMapKey=type
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:storageversion
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=at
// +kubebuilder:printcolumn:name="Registry",type="string",JSONPath=".spec.registryRef"
// +kubebuilder:printcolumn:name="Supervisor",type="string",JSONPath=".spec.supervisor.agentRef"
// +kubebuilder:printcolumn:name="Members",type="string",JSONPath=".status.members"
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"

// AgentTeam is a governed roster of summonable sub-agents plus a supervisor and a spawn budget (M64,
// ADR 0057). The controller resolves + validates the roster against spec.registryRef (the trust
// boundary); at runtime the supervisor delegates to a roster member via the `delegate_to` tool, which
// starts the member as a durable SUB-RUN on the run-worker path — inheriting the invoking user's OBO
// (no re-consent), the conversation, and the trace, bounded by the spawn budget + tenant quota.
type AgentTeam struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AgentTeamSpec   `json:"spec"`
	Status AgentTeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AgentTeamList contains a list of AgentTeam.
type AgentTeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AgentTeam `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *k8sruntime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &AgentTeam{}, &AgentTeamList{})
		return nil
	})
}
